### PR TITLE
Fix: wazo-router-confd has version prefix in API end-points (/1.0)

### PR DESCRIPTION
**Pull request by tranchitella**
Depends-On: https://github.com/wazo-platform/wazo-c4/pull/4

### CODE REVIEW

**Comment by fredericlepied** [comment]
recheck

**Review by alexsosic — DISMISSED** [review]

**Comment by alexsosic** [comment]
Working with C4 integration tests.

**Review by mwolff44 — COMMENTED** [review]
It could be a good idea to have a specific settings for : 
* router url
* router port
* API version

**Comment by tranchitella** [comment]
> It could be a good idea to have a specific settings for :
> 
> * router url
> * router port
> * API version

We are not going to support different API versions, it is a nightmare.
Regarding router URL and PORT, they are configurable via kamailio-local.cfg:
https://github.com/wazo-platform/wazo-c4-router/blob/master/kamailio/kamailio-local.cfg.example#L4

**Comment by mwolff44** [comment]
> > It could be a good idea to have a specific settings for :
> > 
> > * router url
> > * router port
> > * API version
> 
> We are not going to support different API versions, it is a nightmare.
> Regarding router URL and PORT, they are configurable via kamailio-local.cfg:
> https://github.com/wazo-platform/wazo-c4-router/blob/master/kamailio/kamailio-local.cfg.example#L4

it is just when you need to migrate. You have the old version with one API version, and you build the new one with new version ! perhaps it is not necessary !
In your example, you modify the complete url ! but it can make sens !

**Comment by tranchitella** [comment]
recheck

**Review by mwolff44 — APPROVED** [review]

**Comment by tranchitella** [comment]
regate

**Pull request merged**
